# Generated by Django 3.0.2 on 2020-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200706_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='otp_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='otp_valid_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
