# Generated by Django 3.0.2 on 2020-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200707_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
