# Generated by Django 3.0.6 on 2020-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='is_in_found',
            field=models.BooleanField(default=True),
        ),
    ]
