# Generated by Django 3.0.6 on 2020-07-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_missingperson_is_in_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('missing_person_image', models.FileField(blank=True, null=True, upload_to='')),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('founder_person_address', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('founder_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('founder_person_email', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in_found', models.BooleanField(default=True)),
                ('founder_person_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='found_person_updated', to=settings.AUTH_USER_MODEL)),
                ('missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.MissingPerson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='founder_person_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
